name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  BuildSimulation:
    # TODO ***done*** abort this workflow if the git user triggered it is not the release manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Release Manager
        run: |
          if [ "${{ github.actor }}" != "davidhei" ]; then
            echo "This workflow can only be triggered by the release manager. Aborting..."
            exit 1
          fi
      - name: Build
        run: |
          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env